//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.239
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UkrferryDocker.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UkrferryDocker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap barrel {
            get {
                object obj = ResourceManager.GetObject("barrel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barrelGoal {
            get {
                object obj = ResourceManager.GetObject("barrelGoal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap barrelOnGoal {
            get {
                object obj = ResourceManager.GetObject("barrelOnGoal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap box {
            get {
                object obj = ResourceManager.GetObject("box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap box1 {
            get {
                object obj = ResourceManager.GetObject("box1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap boxGoal {
            get {
                object obj = ResourceManager.GetObject("boxGoal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap boxOnGoal {
            get {
                object obj = ResourceManager.GetObject("boxOnGoal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floor {
            get {
                object obj = ResourceManager.GetObject("floor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floorInRoom {
            get {
                object obj = ResourceManager.GetObject("floorInRoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floorInRoomToFloor {
            get {
                object obj = ResourceManager.GetObject("floorInRoomToFloor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floorInRoomToFloorWithWall {
            get {
                object obj = ResourceManager.GetObject("floorInRoomToFloorWithWall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floorsimple {
            get {
                object obj = ResourceManager.GetObject("floorsimple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floorWithTree1 {
            get {
                object obj = ResourceManager.GetObject("floorWithTree1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floorWithTree2 {
            get {
                object obj = ResourceManager.GetObject("floorWithTree2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floorWithTree3 {
            get {
                object obj = ResourceManager.GetObject("floorWithTree3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floorWithWall {
            get {
                object obj = ResourceManager.GetObject("floorWithWall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fontan {
            get {
                object obj = ResourceManager.GetObject("fontan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hank {
            get {
                object obj = ResourceManager.GetObject("hank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hankGoal {
            get {
                object obj = ResourceManager.GetObject("hankGoal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hankOnGoal {
            get {
                object obj = ResourceManager.GetObject("hankOnGoal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap index {
            get {
                object obj = ResourceManager.GetObject("index", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_prn {
            get {
                object obj = ResourceManager.GetObject("logo_prn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manDU {
            get {
                object obj = ResourceManager.GetObject("manDU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manLR {
            get {
                object obj = ResourceManager.GetObject("manLR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manRL {
            get {
                object obj = ResourceManager.GetObject("manRL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap manUD {
            get {
                object obj = ResourceManager.GetObject("manUD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sea {
            get {
                object obj = ResourceManager.GetObject("sea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap seaBorderCorner {
            get {
                object obj = ResourceManager.GetObject("seaBorderCorner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap seaBorderDown {
            get {
                object obj = ResourceManager.GetObject("seaBorderDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap seaBorderLeft {
            get {
                object obj = ResourceManager.GetObject("seaBorderLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap seaBorderUp {
            get {
                object obj = ResourceManager.GetObject("seaBorderUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trapLR {
            get {
                object obj = ResourceManager.GetObject("trapLR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trapToVesselHoriz {
            get {
                object obj = ResourceManager.GetObject("trapToVesselHoriz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trapUD {
            get {
                object obj = ResourceManager.GetObject("trapUD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselBorderLeft {
            get {
                object obj = ResourceManager.GetObject("vesselBorderLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselBorderRigth {
            get {
                object obj = ResourceManager.GetObject("vesselBorderRigth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselFloor {
            get {
                object obj = ResourceManager.GetObject("vesselFloor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizDown {
            get {
                object obj = ResourceManager.GetObject("vesselHorizDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizDownMiddle {
            get {
                object obj = ResourceManager.GetObject("vesselHorizDownMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizFloor {
            get {
                object obj = ResourceManager.GetObject("vesselHorizFloor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizFloor1 {
            get {
                object obj = ResourceManager.GetObject("vesselHorizFloor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizLeftDown {
            get {
                object obj = ResourceManager.GetObject("vesselHorizLeftDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizLeftEndDown {
            get {
                object obj = ResourceManager.GetObject("vesselHorizLeftEndDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizLeftEndDown1 {
            get {
                object obj = ResourceManager.GetObject("vesselHorizLeftEndDown1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizLeftEndDown2 {
            get {
                object obj = ResourceManager.GetObject("vesselHorizLeftEndDown2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizLeftEndMiddle {
            get {
                object obj = ResourceManager.GetObject("vesselHorizLeftEndMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizLeftEndUp {
            get {
                object obj = ResourceManager.GetObject("vesselHorizLeftEndUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizLeftUp {
            get {
                object obj = ResourceManager.GetObject("vesselHorizLeftUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizRigthDown {
            get {
                object obj = ResourceManager.GetObject("vesselHorizRigthDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizRigthEndDown {
            get {
                object obj = ResourceManager.GetObject("vesselHorizRigthEndDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizRigthEndDown1 {
            get {
                object obj = ResourceManager.GetObject("vesselHorizRigthEndDown1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizRigthEndDown2 {
            get {
                object obj = ResourceManager.GetObject("vesselHorizRigthEndDown2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizRigthEndMiddle {
            get {
                object obj = ResourceManager.GetObject("vesselHorizRigthEndMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizRigthEndUp {
            get {
                object obj = ResourceManager.GetObject("vesselHorizRigthEndUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizRigthUp {
            get {
                object obj = ResourceManager.GetObject("vesselHorizRigthUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselHorizUp {
            get {
                object obj = ResourceManager.GetObject("vesselHorizUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselNoseLeft1 {
            get {
                object obj = ResourceManager.GetObject("vesselNoseLeft1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselNoseLeft2 {
            get {
                object obj = ResourceManager.GetObject("vesselNoseLeft2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselNoseMiddle {
            get {
                object obj = ResourceManager.GetObject("vesselNoseMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselNoseMiddleMult {
            get {
                object obj = ResourceManager.GetObject("vesselNoseMiddleMult", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselNoseMiddleMultFloor {
            get {
                object obj = ResourceManager.GetObject("vesselNoseMiddleMultFloor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselNoseMiddleMultFloorWithTrap {
            get {
                object obj = ResourceManager.GetObject("vesselNoseMiddleMultFloorWithTrap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselNoseRigth1 {
            get {
                object obj = ResourceManager.GetObject("vesselNoseRigth1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselNoseRigth2 {
            get {
                object obj = ResourceManager.GetObject("vesselNoseRigth2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselNoseRigth3 {
            get {
                object obj = ResourceManager.GetObject("vesselNoseRigth3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselRearLeft1 {
            get {
                object obj = ResourceManager.GetObject("vesselRearLeft1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselRearLeft2 {
            get {
                object obj = ResourceManager.GetObject("vesselRearLeft2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselRearMiddle {
            get {
                object obj = ResourceManager.GetObject("vesselRearMiddle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselRearMiddleMult {
            get {
                object obj = ResourceManager.GetObject("vesselRearMiddleMult", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselRearMiddleMultFloor {
            get {
                object obj = ResourceManager.GetObject("vesselRearMiddleMultFloor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselRearRigth1 {
            get {
                object obj = ResourceManager.GetObject("vesselRearRigth1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vesselRearRigth2 {
            get {
                object obj = ResourceManager.GetObject("vesselRearRigth2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wall {
            get {
                object obj = ResourceManager.GetObject("wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wall1 {
            get {
                object obj = ResourceManager.GetObject("wall1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wall2 {
            get {
                object obj = ResourceManager.GetObject("wall2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wall3 {
            get {
                object obj = ResourceManager.GetObject("wall3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wall4 {
            get {
                object obj = ResourceManager.GetObject("wall4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wall5 {
            get {
                object obj = ResourceManager.GetObject("wall5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wall6 {
            get {
                object obj = ResourceManager.GetObject("wall6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wall7 {
            get {
                object obj = ResourceManager.GetObject("wall7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wall8 {
            get {
                object obj = ResourceManager.GetObject("wall8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wall9 {
            get {
                object obj = ResourceManager.GetObject("wall9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wallWithTree {
            get {
                object obj = ResourceManager.GetObject("wallWithTree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
